import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import '../globals.css'
import { poppins } from '../fonts'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <main className="flex overflow-hidden h-screen w-screen">
                    {children}
                </main>
            </body>
        </html>
    )
}
