import type { Metadata } from 'next'
import '../globals.css'
import { poppins, ubuntu } from '../fonts'
import Header from '@/components/Partials/Header'
import Footer from '@/components/Partials/Footer'

export const metadata: Metadata = {
    title: 'Jitu!',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${poppins.variable} ${ubuntu.variable}`}>
                <Header />
                <main>{children}</main>
                <Footer />
            </body>
        </html>
    )
}
