import { Metadata } from 'next'
import Visualizer from '@/components/Container/Auth/VisualizerContainer'
import Form from '@/components/Container/Auth/FormContainer'
import SignInIllustartion from '@/assets/img/illust/urban-concentrated-graphic-designer-working-on-computer-in-space.gif'

export const metadata: Metadata = {
    title: 'Jitu! Login',
    description: 'Generated by create next app',
}

export default function LoginPage() {
    return (
        <>
            <Visualizer
                illustration={SignInIllustartion as unknown as string}
                altText={'Illustration'}
            />
            <Form />
        </>
    )
}
