import { Metadata } from 'next'
import AboutContainer from '@/components/Container/Landing/AboutContainer'
import TestimonialsContainer from '@/components/Container/Landing/TestimonialsContainer'
import AboutCTAContainer from '@/components/Container/Landing/AboutCTAContainer'

export const metadata: Metadata = {
    title: 'About Jitu!',
    description: 'Generated by create next app',
}

export default function AboutPage() {
    return (
        <>
            <AboutContainer />
            <TestimonialsContainer />
            <AboutCTAContainer />
        </>
    )
}
