import { Metadata } from 'next'
import ContactContainer from '@/components/Container/Landing/ContactContainer'

export const metadata: Metadata = {
    title: 'JItu! Contact',
    description: 'Generated by create next app',
}

export default function ContactPage() {
    return (
        <>
            <ContactContainer />
        </>
    )
}
